# di seguito le variabili che possono subire variazioni in caso di modifiche all'applicazione, da ricercare in base all'ID
# <span id="pnTemporaryDocument">7 giorni</span> configurazione per file temporanei caricati prima dell'inserimento notifica, definito in storageConfigurations name: PN_TEMPORARY_DOCUMENT in pn-safestorage-v1-api.yaml
# <span id="numberOfPresignedRequest">15</span> pn.delivery.number-of-presigned-request=15 numero di maxItems della preloadRequest
openapi: 3.0.3
info:
  termsOfService: https://selfcare.notifichedigitali.it/termini-di-servizio
  x-api-id: api-internal-b2b-informal-pa # NO EXTERNAL
#  x-api-id: api-internal-b2b-informal-pa # ONLY EXTERNAL
  title: 'Piattaforma Notifiche: API B2B per le notifiche bonarie esposte alle Pubbliche Amministrazioni'
  x-summary: 'Piattaforma Notifiche: API B2B per le notifiche bonarie esposte alle Pubbliche Amministrazioni'
  version: '1.0.0'
  description: #TODO: da aggiornare
    ## Abstract
    API utilizzate dalle pubbliche amministrazioni per __inviare richieste di notifiche bonarie__ e
    __ottenere informazioni in modalità pull__ sullo stato della
    _"richiesta di notifica"_ (accettata o rifiutata) e, in caso di richiesta accettata,
    sulle comunicazioni effettuate, o solo tentate, nei confronti dei destinatari della notifica.
  contact:
    name: 'SEND: supporto enti'
    url: https://pagopa.atlassian.net/servicedesk/customer/portal/5
servers:
  - url: https://api.notifichedigitali.it
    description: Ambiente di produzione
  - url: https://api.uat.notifichedigitali.it
    description: Ambiente di collaudo
tags:
  - name: Messages
    description: >-
      Invocazioni utilizzabili dai mittenti per creare messaggi da utilizzare
      nelle notifiche bonarie.
  - name: NewInformalNotification
    description: >-
      Invocazioni per effettuare il pre-caricamento dei documenti della notifica
      e inviare notifiche bonarie.
  - name: SenderReadInformalNotificationB2B
    description: >-
      Invocazioni utilizzabili dai mittenti per verificare lo stato delle
      richieste di notifica inviate e delle notifiche accettate.
  - name: InformalNotificationTermination
    description: >-
      Invocazioni per interrompere il workflow di una notifica non legale in
      stato di attesa o accettata.
  - name: HealthCheck
    description: >-
      Invocazioni per sapere lo stato del microservizio
paths:
  /status:
    get:
      summary: status path
      description: status path per verificare lo stato di Piattaforma Notifiche
      tags:
        - HealthCheck
      operationId: status
      responses:
        '200':
          description: Ok
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/PnStatusResponse'
              example:
                functionalities:
                  - NOTIFICATION_CREATE
                  - NOTIFICATION_VISUALIZATION
                  - NOTIFICATION_WORKFLOW
                openIncidents: [ ]
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/PnStatusResponse'
              example:
                functionalities:
                  - NOTIFICATION_CREATE
                  - NOTIFICATION_VISUALIZATION
                  - NOTIFICATION_WORKFLOW
                openIncidents:
                  - functionality: NOTIFICATION_CREATE
                    status: KO
                    startDate: '2019-08-24T14:15:22Z'
  ###########################################################################################
  ###                          GESTIONE PRECARICAMENTO ALLEGATI                           ###
  ###########################################################################################
  "/delivery/v1/attachments/preload":
    post:
      summary: Richiesta di pre-caricamento dei documenti della notifica bonaria
      description: >-
        Operazione che richiede a Piattaforma Notifica le informazioni e le autorizzazioni necessarie 
        a precaricare uno o più file da allegare a una notifica bonaria. <br/>
      tags:
        - NewInformalNotification
      operationId: informalPresignedUploadRequest
      parameters: # NO EXTERNAL
        - $ref: '#/components/parameters/uidAuthFleet'          # NO EXTERNAL
        - $ref: '#/components/parameters/cxTypeAuthFleet'       # NO EXTERNAL
        - $ref: '#/components/parameters/cxIdAuthFleet'         # NO EXTERNAL
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/InformalPreLoadRequest"
              minItems: 1
              maxItems: 15
        required: true
      responses:
        '200':
          description: Informazioni per il caricamento degli allegati tramite URL presigned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/InformalPreLoadResponse"
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

  ###########################################################################################
  ###                          GESTIONE MESSAGGI                                          ###
  ###########################################################################################

  "/delivery/v1/messages":
    post:
      tags:
        - Messages
      summary: Crea un nuovo template di messaggio
      description: |
        Salva il contenuto del messaggio in modo sicuro e ottiene un messageId da utilizzare per creare una notifica bonaria.
      operationId: newMessage
      parameters:                                             # NO EXTERNAL
        - $ref: '#/components/parameters/uidAuthFleet'        # NO EXTERNAL
        - $ref: '#/components/parameters/cxTypeAuthFleet'     # NO EXTERNAL
        - $ref: '#/components/parameters/cxIdAuthFleet'       # NO EXTERNAL
        - $ref: '#/components/parameters/cxGroupsAuthFleet'   # NO EXTERNAL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMessageRequest'
            example:
              primaryMessage:
                subject: Oggetto IT
                longBody: Test body IT
                shortBody: Short IT
                language: IT
      responses:
        '201':
          description: Message created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
              example:
                primaryMessage:
                  subject: Oggetto IT
                  longBody: Test body IT
                  shortBody: Short IT
                  language: IT
                messageId: 94484841-57e5-496f-8f2d-eec053c539e3
                createdAt: "2026-06-26T13:35:00.000Z"
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  "/delivery/v1/messages/{messageId}":
    get:
      tags:
        - Messages
      summary: Recupera i dati di un messaggio
      description: Recupera il contenuto di un messaggio precedentemente creato dato il suo id.
      operationId: messageById
      parameters:
        - name: messageId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - $ref: '#/components/parameters/uidAuthFleet'      # NO EXTERNAL
        - $ref: '#/components/parameters/cxTypeAuthFleet'   # NO EXTERNAL
        - $ref: '#/components/parameters/cxIdAuthFleet'     # NO EXTERNAL
        - $ref: '#/components/parameters/cxGroupsAuthFleet' # NO EXTERNAL
      responses:
        '200':
          description: Message details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
              example:
                primaryMessage:
                  subject: Oggetto IT
                  longBody: Test body IT
                  shortBody: Short IT
                  language: IT
                messageId: 94484841-57e5-496f-8f2d-eec053c539e3
                createdAt: "2026-06-26T13:35:00.000Z"
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Message not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

    ###########################################################################################
    ###                          CREAZIONE RICHIESTE DI NOTIFICA                            ###
    ###########################################################################################
  "/delivery/v1/requests":
    post:
      summary: Richiesta sottomissione di una nuova comunicazione bonaria
      description: |-
        Operazione utilizzata dalla Pubblica Amministrazione per richiedere l'invio di una notifica bonaria.

        La restituzione di uno stato HTTP 202 significa solo che la richiesta è sintatticamente
        valida, non che la richiesta sia stata validata ed accettata. <br/>
        Per conoscere lo stato di accettazione della richiesta di notifica bisogna utilizzare l'operazione
        getInformalNotificationRequestStatusV1. <br/>

        <details no-external>
        <summary><b> Attributi progettazione di alto livello </b></summary>
        | Proprietà                | Valore             |
        | -----------------------: | :----------------- |
        | __Intended usage__       | B2B, WEB           |
        | __Modalità interazione__ | Sincrona           |
        | __TPS (stimato)__        | 5 richieste/sec    |
        | __Idempotenza__          | No                 |
        | __Read/Write intensive__ | Write              |
        | __Cachable__             | No                 |
        </details>
      tags:
        - NewInformalNotification
      operationId: sendNewInformalNotificationV1
      parameters: # NO EXTERNAL
        - $ref: '#/components/parameters/uidAuthFleet'                # NO EXTERNAL
        - $ref: '#/components/parameters/cxTypeAuthFleet'             # NO EXTERNAL
        - $ref: '#/components/parameters/cxIdAuthFleet'               # NO EXTERNAL
        - $ref: '#/components/parameters/cxGroupsAuthFleet'           # NO EXTERNAL
        - $ref: '#/components/parameters/headerSourceChannel'         # NO EXTERNAL
        - $ref: '#/components/parameters/headerSourceChannelDetails'  # NO EXTERNAL
        - $ref: '#/components/parameters/headerNotificationVersion'   # NO EXTERNAL
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./schemas-pn-notification.yaml#/components/schemas/InformalNotificationRequestV1"
        required: true
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewInformalNotificationResponse"
              example:
                notificationRequestId: TVBNRS1RR1RHLVZNVEUtMjAyNjA2LUgtQQ==
                paProtocolNumber: "302110111988283231"
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '409':
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'


    ###########################################################################################
    ###                        VERIFICA STATO RICHIESTE DI NOTIFICA                         ###
    ###########################################################################################
    get:
      operationId: getInformalNotificationRequestStatusV1                       # NO EXTERNAL
#      operationId: retrieveInformalNotificationRequestStatusV1                # ONLY EXTERNAL
      tags:
        - SenderReadInformalNotificationB2B
      summary: Verifica accettazione richiesta notifica
      description: >-
        Questa operazione serve per verificare se la richiesta di notifica è stata accettata e ottenere
        lo IUN associato a tale richiesta. <br/>
        Bisogna specificare il parametro _notificationRequestId_  oppure la coppia costituita dai parametri 
        _paProtocolNumber_ e _idempotenceToken_. <br/>
      parameters:
        - $ref: '#/components/parameters/uidAuthFleet'              # NO EXTERNAL
        - $ref: '#/components/parameters/cxTypeAuthFleet'           # NO EXTERNAL
        - $ref: '#/components/parameters/cxIdAuthFleet'             # NO EXTERNAL
        - $ref: '#/components/parameters/cxGroupsAuthFleet'         # NO EXTERNAL
        - $ref: '#/components/parameters/notificationRequestId'
        - $ref: '#/components/parameters/paProtocolNumber'
        - $ref: '#/components/parameters/idempotenceToken'
      responses:
        '200':
          description: Stato corrente della richiesta di notifica informale
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewInformalNotificationRequestStatusResponseV1"
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

      ###########################################################################################
      ###                     DOWNLOAD DOCUMENTI E ALLEGATI PER PAGAMENTO                     ###
      ###########################################################################################

  "/delivery/v1/notifications/sent/{iun}/attachments/documents/{docIdx}":
    get:
      description: |-
        Download documento notificato

        <details no-external>
        <summary><b> Attributi progettazione di alto livello </b></summary>
        | Proprietà                | Valore             |
        | -----------------------: | :----------------- |
        | __Intended usage__       | B2B, WEB           |
        | __Modalità interazione__ | Sincrona           |
        | __TPS (stimato)__        |                    |
        | __Idempotenza__          | Si                 |
        | __Read/Write intensive__ | Read               |
        | __Cachable__             | No                 |
        </details>
      summary: Download documento notificato
      tags:
        - SenderReadInformalNotificationB2B
      operationId: getSentInformalNotificationDocument                                      # NO EXTERNAL
#      operationId: retrieveSentInformalNotificationDocument                                # ONLY EXTERNAL
      parameters:
        - $ref: '#/components/parameters/uidAuthFleet'           # NO EXTERNAL
        - $ref: '#/components/parameters/cxTypeAuthFleet'        # NO EXTERNAL
        - $ref: '#/components/parameters/cxIdAuthFleet'          # NO EXTERNAL
        - $ref: '#/components/parameters/cxGroupsAuthFleet'      # NO EXTERNAL
        - $ref: './parameters-notification-search.yaml#/components/parameters/pathInformalIun'
        - $ref: '#/components/parameters/pathDocumentIdx'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './schemas-pn-notification.yaml#/components/schemas/NotificationAttachmentDownloadMetadataResponse'
              example:
                filename: AvvisoPagamento.pdf
                contentType: application/pdf
                contentLength: 54092
                sha256: 1QKD/Ks6BohyQ+bgMxHf9NrpNhVmGUPxRYE1aerU4JQ=
                url: https://pn-safestorage.../PN_NOTIFICATION_ATTACHMENTS-39a690b91d8a4d1fa3d6eae5f8246f57.pdf?X-Amz-...
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

  "/delivery/v1/notifications/sent/{iun}/attachments/payment/{recipientIdx}/{attachmentName}":
    get:
      description: Download allegato per pagamento
      summary: Download allegato per pagamento
      tags:
        - SenderReadInformalNotificationB2B
      operationId: getSentInformalNotificationAttachment                                      # NO EXTERNAL
#      operationId: retrieveSentInformalNotificationAttachment                                # ONLY EXTERNAL
      parameters:
        - $ref: '#/components/parameters/uidAuthFleet'              # NO EXTERNAL
        - $ref: '#/components/parameters/cxTypeAuthFleet'           # NO EXTERNAL
        - $ref: '#/components/parameters/cxIdAuthFleet'             # NO EXTERNAL
        - $ref: '#/components/parameters/cxGroupsAuthFleet'         # NO EXTERNAL
        - $ref: './parameters-notification-search.yaml#/components/parameters/pathInformalIun'
        - $ref: '#/components/parameters/pathRecipientIdx'
        - $ref: '#/components/parameters/pathAttachmentName'
        - $ref: '#/components/parameters/attachmentIdx'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './schemas-pn-notification.yaml#/components/schemas/NotificationAttachmentDownloadMetadataResponse'
              example:
                filename: AvvisoPagoPA.pdf
                contentType: application/pdf
                contentLength: 54092
                sha256: 1QKD/Ks6BohyQ+bgMxHf9NrpNhVmGUPxRYE1aerU4JQ=
                url: https://pn-safestorage.../PN_NOTIFICATION_ATTACHMENTS-fec693663bb04300aa8d0af615d21e66.pdf?X-Amz-...
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

    ###########################################################################################
    ###                             INTERRUZIONE DEL WORKFLOW                               ###
    ###########################################################################################
  "/delivery/v1/notifications/sent/{iun}/terminate":
    post:
      tags:
        - InformalNotificationTermination
      summary: Interruzione workflow notifica per IUN
      description: >-
        Permette all\'Ente di interrompere il workflow di una comunicazione non 
        legale identificata dallo IUN specificato nel path. La notifica passerà allo stato COMPLETED.
      operationId: terminateInformalWorkflow
      parameters:
        - $ref: '#/components/parameters/uidAuthFleet' # NO EXTERNAL
        - $ref: '#/components/parameters/cxTypeAuthFleet' # NO EXTERNAL
        - $ref: '#/components/parameters/cxIdAuthFleet' # NO EXTERNAL
        - $ref: '#/components/parameters/cxGroupsAuthFleet' # NO EXTERNAL
        - $ref: './parameters-notification-search.yaml#/components/parameters/pathInformalIun'
      responses:
        '202':
          description: Accepted - Richiesta interruzione presa in carico
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TerminationRequestStatus"
              example:
                status: OK
                details:
                  - code: NOTIFICATION_TERMINATION_ACCEPTED
                    level: INFO
                    detail: Richiesta di interruzione presa in carico
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  ###########################################################################################
  ###                          RICERCA NOTIFICHE BONARIE INVIATE                          ###
  ###########################################################################################
  "/delivery/v1/notifications/sent/{iun}":
    get:
      summary: 'Mittente: lettura dettagli notifica versione 1'
      description: |-
        Questa operazione permette di leggere tutti i dettagli di una notifica accettata. <br/>
        
        <details no-external>
        <summary><b> Attributi progettazione di alto livello </b></summary>
        | Proprietà                | Valore             |
        | -----------------------: | :----------------- |
        | __Intended usage__       | B2B, WEB           |
        | __Modalità interazione__ | Sincrona           |
        | __TPS (stimato)__        |                    |
        | __Idempotenza__          | Si                 |
        | __Read/Write intensive__ | Read               |
        | __Cachable__             | No                 |
        </details>
      tags:
        - SenderReadInformalNotificationB2B
      operationId: getSentInformalNotificationV1
      parameters:
        - $ref: '#/components/parameters/uidAuthFleet'            # NO EXTERNAL
        - $ref: '#/components/parameters/cxTypeAuthFleet'         # NO EXTERNAL
        - $ref: '#/components/parameters/cxIdAuthFleet'           # NO EXTERNAL
        - $ref: '#/components/parameters/cxGroupsAuthFleet'       # NO EXTERNAL
        - $ref: './parameters-notification-search.yaml#/components/parameters/pathInformalIun'
        - $ref: './parameters-notification-search.yaml#/components/parameters/retrieveMessage'
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/FullSentInformalNotificationV1"
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

components:
  parameters:
    ############################################################################################
    ###                     PARAMETRO VERSIONE CREAZIONE NOTIFICA                            ###
    ############################################################################################
    headerNotificationVersion:                                                      # NO EXTERNAL
      name: x-pagopa-pn-notification-version                                        # NO EXTERNAL
      in: header                                                                    # NO EXTERNAL
      description: Notification creation version                                    # NO EXTERNAL
      required: false                                                               # NO EXTERNAL
      schema:                                                                       # NO EXTERNAL
        type: string                                                                # NO EXTERNAL

    ############################################################################################
    ###                     PARAMETRO SORGENTE CREAZIONE NOTIFICA                            ###
    ############################################################################################
    headerSourceChannel:                                                            # NO EXTERNAL
      $ref: './remote-refs.yaml#/components/parameters/headerSourceChannel'         # NO EXTERNAL

    headerSourceChannelDetails:                                                     # NO EXTERNAL
      $ref: './remote-refs.yaml#/components/parameters/headerSourceChannelDetails'  # NO EXTERNAL

    ############################################################################################
    ###                     PARAMETRI DI AUTENTICAZIONE E AUTORIZZAZIONE                     ###
    ############################################################################################
    cxTypeAuthFleet:                                                                # NO EXTERNAL
      $ref: './remote-refs.yaml#/components/parameters/cxTypeAuthFleet'             # NO EXTERNAL
    cxIdAuthFleet:                                                                  # NO EXTERNAL
      $ref: './remote-refs.yaml#/components/parameters/cxIdAuthFleet'               # NO EXTERNAL
    cxGroupsAuthFleet:                                                              # NO EXTERNAL
      $ref: './remote-refs.yaml#/components/parameters/cxGroupsAuthFleet'           # NO EXTERNAL
    uidAuthFleet:                                                                   # NO EXTERNAL
      $ref: './remote-refs.yaml#/components/parameters/uidAuthFleet'                # NO EXTERNAL

    ############################################################################################
    ###                       PARAMETRI RICERCA RICHIESTA DI NOTIFICA                        ###
    ############################################################################################
    notificationRequestId:
      in: query
      required: false
      name: notificationRequestId
      example: TVBNRS1RR1RHLVZNVEUtMjAyNjA2LUgtQQ==
      schema:
        $ref: './schemas-pn-notification.yaml#/components/schemas/NotificationRequestId'

    paProtocolNumber:
      name: paProtocolNumber
      in: query
      required: false
      schema:
        $ref: './schemas-pn-notification.yaml#/components/schemas/PaProtocolNumber'

    idempotenceToken:
      name: idempotenceToken
      in: query
      required: false
      schema:
        $ref: './schemas-pn-notification.yaml#/components/schemas/IdempotenceToken'

    ############################################################################################
    ###                             PARAMETRI DOWNLOAD DOCUMENTI                             ###
    ############################################################################################
    pathDocumentIdx:
      name: docIdx
      description: indice del documento nella lista partendo da 0.
      in: path
      required: true
      schema:
        type: integer
        format: int32

    pathRecipientIdx:
      name: recipientIdx
      description: indice del destinatario nella lista partendo da 0.
      in: path
      required: true
      schema:
        type: integer
        format: int32

    pathAttachmentName:
      name: attachmentName
      description: Tipologia del pagamento allegato alla notifica. Valore possibile PAGOPA
      in: path
      required: true
      schema:
        type: string
        pattern: "PAGOPA"

    attachmentIdx:
      in: query
      name: attachmentIdx
      description: indice del documento di pagamento partendo da 0
      required: false
      schema:
        type: integer
        format: int32

  schemas:
    ###########################################################################################
    ###                             DTO PRECARICAMENTO ALLEGATI                             ###
    ###########################################################################################
    InformalPreLoadRequest:
      title: Richiesta di precaricamento di un File
      type: object
      required:
        - sha256
      properties:
        preloadIdx:
          title: Id della richiesta di precaricamento di un file
          description: >-
            Identificativo univoco all'interno della request HTTP, serve per correlare la risposta.
            Stringa alfanumerica con caratteri utilizzabili in un nome file.
          type: string
          minLength: 1
          maxLength: 512
          pattern: ^[a-zA-Z0-9._-]{1,512}$
        contentType:
          title: MIME type del file che verrà caricato
          description: >-
            Il MIME type dell'allegato che dovrà essere caricato. Attualmente sono supportati
              - application/pdf
          type: string
          minLength: 15
          maxLength: 16
          pattern: ^application\/(pdf)$
        sha256:
          title: checksum sha256 del file che verrà caricato
          description: >-
            checksum sha256, codificato in base 64, del contenuto binario del file che verrà
            caricato
          type: string
          example: 'jezIVxlG1M1woCSUngM6KipUN3/p8cG5RMIPnuEanlE='
          minLength: 44
          maxLength: 44
          pattern: ^[A-Za-z0-9+\/]{43}=|[A-Za-z0-9+\/]{44}$

    InformalPreLoadResponse:
      title: Informazioni per il caricamento file
      description: >-
        Per ogni richiesta che è stata fatta viene fornito un presigned URL e le 
        informazioni per usarlo.
      type: object
      properties:
        preloadIdx:
          description: per correlazione con la richiesta. Stringa alfanumerica con caratteri utilizzabili in un file.
          type: string
          minLength: 1
          maxLength: 512
          pattern: ^[a-zA-Z0-9._-]{1,512}$
        secret:
          description: >-
            Token aggiuntivo per far si che sia necessario intercettare anche gli 
            header e non solo l'URL di upload del contenuto del documento.
          example: AZ23RF12
          type: string
        httpMethod:
          description: >-
            Indica se per l'upload del contenuto file bisogna utilizzare il metodo PUT o POST
          type: string
          example: PUT
          enum:
            - POST
            - PUT
        url:
          description: >-
            URL a cui effettuare l'upload del contenuto del documento.
          type: string
          example: 'https://preloadpn.aws.amazon.......'
        key:
          description: >-
            la chiave restituita sarà globalmente unica e andrà utilizzata nella richiesta 
            di notifica.
          example: 'PN_NOTIFICATION_ATTACHMENTS-0001-301W-B9CB-9U72-WIKD'
          type: string

    ###########################################################################################
    ###                              DTO MESSAGGI                                           ###
    ###########################################################################################

    NewMessageRequest:
      type: object
      required: [ primaryMessage ]
      properties:
        primaryMessage:
          allOf:
            - $ref: './schemas-pn-notification.yaml#/components/schemas/LocalizedContent'
            - description: Contenuto principale del messaggio, deve essere in lingua italiana
        additionalMessage:
          allOf:
            - $ref: './schemas-pn-notification.yaml#/components/schemas/LocalizedContent'
            - description: Contenuto aggiuntivo del messaggio, opzionale, può essere in una lingua diversa dall'italiano
    MessageResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/NewMessageRequest'
        - type: object
          properties:
            messageId:
              description: Identificativo univoco del messaggio, da utilizzare per creare una notifica bonaria
              type: string
              format: uuid
            createdAt:
              description: Data e ora di creazione del messaggio
              type: string
              format: date-time

    ###########################################################################################
    ###                              DTO RICHIESTE DI NOTIFICA                              ###
    ###########################################################################################
    NewInformalNotificationResponse:
      $ref: "./schemas-pn-notification.yaml#/components/schemas/NewNotificationResponse"


    NewInformalNotificationRequestStatusResponseV1:
      allOf:
        - $ref: "./schemas-pn-notification.yaml#/components/schemas/InformalNotificationRequestV1"
        - type: object
          required:
            - notificationRequestId
            - notificationRequestStatus
          properties:
            notificationRequestId:
              $ref: "./schemas-pn-notification.yaml#/components/schemas/NotificationRequestId"
            notificationRequestStatus:
              description: >-
                - __WAITING__: in attesa di essere valutata
                - __ACCEPTED__: richiesta di notifica accettata, lo IUN è valorizzato
                - __REFUSED__: richiesta di notifica rifiutata, è valorizzato il campo _errors_
              type: string
            retryAfter:
              type: integer
              format: int32
              description: >-
                Numero di secondi da attendere prima di effettuare una nuova richiesta per 
                la stessa entità; valorizzato quando lo status è __WAITING__.
            iun:
              $ref: "./schemas-pn-notification.yaml#/components/schemas/InformalIUN"
            errors:
              description: >-
                Elenco degli errori che hanno causato il rifiuto della richiesta di notifica
              type: array
              items:
                $ref: '#/components/schemas/NotificationRequestRefusedProblemError'

    NotificationRequestRefusedProblemError:
      allOf:
        - $ref: '#/components/schemas/ProblemError'
        - type: object
          required:
            - code
          properties:
            recIndex:
              description: Index destinatario notifica digitale
              type: integer
              format: int32

    ###########################################################################################
    ###                       DTO RICHIESTE DI TERMINAZIONE WORKFLOW                        ###
    ###########################################################################################

    TerminationRequestStatus:
      description: Risposta alla richiesta di interruzione del workflow di una notifica non legale.
      type: object
      required: [ status ]
      properties:
        status:
          description: >
            Termination request status:
              - OK
          type: string
        details:
          type: array
          maxItems: 9999
          items:
            $ref: '#/components/schemas/StatusDetail'

    StatusDetail:
      description: >-
        Informazione di dettaglio sullo stato di una richiesta
      type: object
      required:
        - code
      properties:
        code:
          description: Codice interno di errore o avvertimento, in formato leggibile
          example: NOTIFICATION_TERMINATION_ACCEPTED, NOTIFICATION_ALREADY_TERMINATED, etc.
          type: string
        level:
          description: |
            livello informativo del dettaglio di stato: INFO,WARN, ERR
            ERR (error) di default
          example: INFO
          type: string
        detail:
          description: >-
            Spiegazione specifica per questa occorrenza del problema.
          example: Parametro non valido
          type: string

    ###########################################################################################
    ###                              DTO STATUS                                            ###
    ###########################################################################################

    PnStatusResponse:
      title: Stato attuale di PN
      description: >-
        Elenco delle funzionalità della piattaforma ed elenco dei disservizi
        noti e attivi  al momento della richiesta. I disservizi
        (_openIncidents_) segnalati sono al più uno  per funzionalità; gli
        attributi _endDate_ e _legalFactId_ non saranno valorizzati.
      type: object
      required:
        - functionalities
        - openIncidents
      properties:
        status:
          description: Bad Request
          example: 400
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: The server cannot process the request
          example: Bad Request
          maxLength: 64
          pattern: ^[ -~]{0,64}$
          type: string
        detail:
          description: The server cannot process the request
          example: Bad Request
          maxLength: 4096
          pattern: ^.{0,4096}$
          type: string
        functionalities:
          title: elenco funzionalità di PN
          description: >-
            Un array che comprende tutti i possibili valori dell'enum
            _PnFunctionality_
          type: array
          items:
            $ref: '#/components/schemas/PnFunctionality'
        openIncidents:
          title: elenco disservizi correnti
          description: Al più uno per funzionalità
          type: array
          items:
            $ref: '#/components/schemas/PnDowntimeEntry'
    PnFunctionality:
      title: Funzionalità di PN
      description: >-
        - __NOTIFICATION_CREATE__: la possibilità di creare nuove notifiche.

        - __NOTIFICATION_VISUALIZATION__: la possibilità di visualizzare le
        notifiche e scaricare gli atti. 

        - __NOTIFICATION_WORKFLOW__: l'avanzamento del processo di notifica.
      type: string
      enum:
        - NOTIFICATION_CREATE
        - NOTIFICATION_VISUALIZATION
        - NOTIFICATION_WORKFLOW
      x-enum-varnames:
        - NOTIFICATION_CREATE
        - NOTIFICATION_VISUALIZATION
        - NOTIFICATION_WORKFLOW
    PnFunctionalityStatus:
      type: string
      enum:
        - KO
        - OK
    PnDowntimeEntry:
      title: Dati relativi ad un disservizio di PN.
      type: object
      required:
        - functionality
        - status
        - startDate
      properties:
        functionality:
          $ref: '#/components/schemas/PnFunctionality'
        status:
          $ref: '#/components/schemas/PnFunctionalityStatus'
        startDate:
          title: data inizio disservizio
          type: string
          format: date-time
        endDate:
          title: data fine disservizio
          description: >-
            se il disservizio è ancora attivo questo campo sarà assente o con
            valore _null_
          type: string
          format: date-time
        legalFactId:
          title: id dell'atto opponibile a terzi
          description: >-
            Se assente o valorizzato _null_ indica che l'atto opponibile a terzi
            non è ancora disponibile. Questo avviene per i disservizi ancora
            aperti e per i disservizi  terminati da pochi minuti. <br/> Questo
            valore è da utilizzare con l'API _getLegalFact_ di questo stesso
            servizio.
          type: string
        fileAvailable:
          type: boolean

    ###########################################################################################
    ###                              DTO NOTIFICA CON DETTAGLI                              ###
    ###########################################################################################
    FullSentInformalNotificationV1:
      description: >-
        Le informazioni riguardanti una notifica (richiesta di notifica accettata) e il 
        processo di inoltro della notifica verso il cittadino.
      allOf:
        - $ref: './schemas-pn-notification.yaml#/components/schemas/InformalSentNotificationV1'
        - type: object
          required:
            - notificationStatus
            - notificationStatusHistory
            - timeline
          properties:
            notificationStatus:
              $ref: '#/components/schemas/InformalNotificationStatusV1'
            notificationStatusHistory:
              $ref: '#/components/schemas/InformalNotificationStatusHistoryV1'
            timeline:
              description: >-
                elenco dettagliato di tutto ciò che è accaduto durrante il processo di notifica
              type: array
              items:
                $ref: '#/components/schemas/InformalTimelineElementV1'
            recipientIds: # NO EXTERNAL
              description: Lista degli identificativi anonimizzati dei destinatari      # NO EXTERNAL
              type: array                                                               # NO EXTERNAL
              items: # NO EXTERNAL
                type: string                                                            # NO EXTERNAL
            sourceChannel: # NO EXTERNAL
              type: string                                                              # NO EXTERNAL
              description: Canale sorgente della richiesta di notifica                  # NO EXTERNAL
            sourceChannelDetails: # NO EXTERNAL
              type: string                                                              # NO EXTERNAL
              description: Dettagli del canale sorgente della richiesta di notifica     # NO EXTERNAL

    Problem:
      $ref: './remote-refs.yaml#/components/schemas/Problem'
    ProblemError:
      $ref: './remote-refs.yaml#/components/schemas/ProblemError'
    InformalTimelineElementV1:
      $ref: './remote-refs.yaml#/components/schemas/InformalTimelineElementV1'
    InformalNotificationStatusV1:
      $ref: './remote-refs.yaml#/components/schemas/InformalNotificationStatusV1'
    InformalNotificationStatusHistoryV1:
      $ref: './remote-refs.yaml#/components/schemas/InformalNotificationStatusHistoryV1'

#  securitySchemes:        # ONLY EXTERNAL
#    ApiKeyAuth:           # ONLY EXTERNAL
#      type: apiKey        # ONLY EXTERNAL
#      in: header          # ONLY EXTERNAL
#      name: x-api-key     # ONLY EXTERNAL

#security:                 # ONLY EXTERNAL
#  - ApiKeyAuth: [] # use the same name as under securitySchemes    # ONLY EXTERNAL