openapi: 3.0.3
info:
  termsOfService: https://selfcare.notifichedigitali.it/termini-di-servizio
  x-api-id: api-internal-b2b-informal-pa
  title: 'Piattaforma Notifiche: API B2B per le notifiche bonarie esposte alle Pubbliche Amministrazioni'
  x-summary: 'Piattaforma Notifiche: API B2B per le notifiche bonarie esposte alle Pubbliche Amministrazioni'
  version: 1.0.0
  description: API utilizzate dalle pubbliche amministrazioni per __inviare richieste di notifiche bonarie__ e __ottenere informazioni in modalità pull__ sullo stato della _"richiesta di notifica"_ (accettata o rifiutata) e, in caso di richiesta accettata, sulle comunicazioni effettuate, o solo tentate, nei confronti dei destinatari della notifica.
  contact:
    name: 'SEND: supporto enti'
    url: https://pagopa.atlassian.net/servicedesk/customer/portal/5
servers:
  - url: https://api.notifichedigitali.it/informal
    description: Ambiente di produzione
  - url: https://api.uat.notifichedigitali.it/informal
    description: Ambiente di collaudo
security:
  - ApiKeyAuth: []
tags:
  - name: Messages
    description: Invocazioni utilizzabili dai mittenti per creare messaggi da utilizzare nelle notifiche bonarie.
  - name: NewInformalNotification
    description: Invocazioni per effettuare il pre-caricamento dei documenti della notifica e inviare notifiche bonarie.
  - name: SenderReadInformalNotificationB2B
    description: Invocazioni utilizzabili dai mittenti per verificare lo stato delle richieste di notifica inviate e delle notifiche accettate.
  - name: HealthCheck
    description: Invocazioni per sapere lo stato del microservizio
paths:
  /status:
    get:
      summary: status path
      description: status path per verificare lo stato di Piattaforma Notifiche
      tags:
        - HealthCheck
      operationId: status
      responses:
        '200':
          description: Ok
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/PnStatusResponse'
              example:
                functionalities:
                  - NOTIFICATION_CREATE
                  - NOTIFICATION_VISUALIZATION
                  - NOTIFICATION_WORKFLOW
                openIncidents: []
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/PnStatusResponse'
              example:
                functionalities:
                  - NOTIFICATION_CREATE
                  - NOTIFICATION_VISUALIZATION
                  - NOTIFICATION_WORKFLOW
                openIncidents:
                  - functionality: NOTIFICATION_CREATE
                    status: KO
                    startDate: '2019-08-24T14:15:22Z'
  /delivery/v1/attachments/preload:
    post:
      summary: Richiesta di pre-caricamento dei documenti della notifica bonaria
      description: Operazione che richiede a Piattaforma Notifica le informazioni e le autorizzazioni necessarie  a precaricare uno o più file da allegare a una notifica bonaria. <br/>
      tags:
        - NewInformalNotification
      operationId: informalPresignedUploadRequest
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/InformalPreLoadRequest'
              minItems: 1
              maxItems: 15
        required: true
      responses:
        '200':
          description: Informazioni per il caricamento degli allegati tramite URL presigned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InformalPreLoadResponse'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /delivery/v1/messages:
    post:
      tags:
        - Messages
      summary: Crea un nuovo template di messaggio
      description: |
        Salva il contenuto del messaggio in modo sicuro e ottiene un messageId da utilizzare per creare una notifica bonaria.
      operationId: newMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMessageRequest'
            example:
              primaryMessage:
                subject: Oggetto IT
                longBody: Testo del messaggio da inviare al destinatario. Deve avere lunghezza superiore a 80 caratteri.
                shortBody: Short IT
                language: IT
      responses:
        '201':
          description: Message created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
              example:
                primaryMessage:
                  subject: Oggetto IT
                  longBody: Testo del messaggio da inviare al destinatario. Deve avere lunghezza superiore a 80 caratteri.
                  shortBody: Short IT
                  language: IT
                messageId: 94484841-57e5-496f-8f2d-eec053c539e3
                createdAt: '2026-06-26T13:35:00.000Z'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /delivery/v1/messages/{messageId}:
    get:
      tags:
        - Messages
      summary: Recupera i dati di un messaggio
      description: Recupera il contenuto di un messaggio precedentemente creato dato il suo id.
      operationId: messageById
      parameters:
        - name: messageId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Message details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
              example:
                primaryMessage:
                  subject: Oggetto IT
                  longBody: Testo del messaggio da inviare al destinatario. Deve avere lunghezza superiore a 80 caratteri.
                  shortBody: Short more than 10 characters
                  language: IT
                messageId: 94484841-57e5-496f-8f2d-eec053c539e3
                createdAt: '2026-06-26T13:35:00.000Z'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Message not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /delivery/v1/requests:
    post:
      summary: Richiesta sottomissione di una nuova comunicazione bonaria
      description: |-
        Operazione utilizzata dalla Pubblica Amministrazione per richiedere l'invio di una notifica bonaria.

        La restituzione di uno stato HTTP 202 significa solo che la richiesta è sintatticamente
        valida, non che la richiesta sia stata validata ed accettata. <br/>
        Per conoscere lo stato di accettazione della richiesta di notifica bisogna utilizzare l'operazione
        getInformalNotificationRequestStatusV1. <br/>
      tags:
        - NewInformalNotification
      operationId: sendNewInformalNotificationV1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InformalNotificationRequestV1'
        required: true
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewNotificationResponse'
              example:
                notificationRequestId: TVBNRS1RR1RHLVZNVEUtMjAyNjA2LUgtQQ==
                paProtocolNumber: '302110111988283231'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '409':
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    get:
      operationId: retrieveInformalNotificationRequestStatusV1
      tags:
        - SenderReadInformalNotificationB2B
      summary: Verifica accettazione richiesta notifica
      description: Questa operazione serve per verificare se la richiesta di notifica è stata accettata e ottenere lo IUN associato a tale richiesta. <br/> Bisogna specificare il parametro _notificationRequestId_  oppure la coppia costituita dai parametri  _paProtocolNumber_ e _idempotenceToken_. <br/>
      parameters:
        - $ref: '#/components/parameters/notificationRequestId'
        - $ref: '#/components/parameters/paProtocolNumber'
        - $ref: '#/components/parameters/idempotenceToken'
      responses:
        '200':
          description: Stato corrente della richiesta di notifica informale
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewInformalNotificationRequestStatusResponseV1'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  parameters:
    notificationRequestId:
      in: query
      required: false
      name: notificationRequestId
      example: TVBNRS1RR1RHLVZNVEUtMjAyNjA2LUgtQQ==
      schema:
        $ref: '#/components/schemas/NotificationRequestId'
    paProtocolNumber:
      name: paProtocolNumber
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/PaProtocolNumber'
    idempotenceToken:
      name: idempotenceToken
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/IdempotenceToken'
  schemas:
    InformalPreLoadRequest:
      title: Richiesta di precaricamento di un File
      type: object
      required:
        - sha256
      properties:
        preloadIdx:
          title: Id della richiesta di precaricamento di un file
          description: Identificativo univoco all'interno della request HTTP, serve per correlare la risposta. Stringa alfanumerica con caratteri utilizzabili in un nome file.
          type: string
          minLength: 1
          maxLength: 512
          pattern: ^[a-zA-Z0-9._-]{1,512}$
        contentType:
          title: MIME type del file che verrà caricato
          description: |-
            Il MIME type dell'allegato che dovrà essere caricato. Attualmente sono supportati
              - application/pdf
          type: string
          minLength: 15
          maxLength: 16
          pattern: ^application\/(pdf)$
        sha256:
          title: checksum sha256 del file che verrà caricato
          description: checksum sha256, codificato in base 64, del contenuto binario del file che verrà caricato
          type: string
          example: jezIVxlG1M1woCSUngM6KipUN3/p8cG5RMIPnuEanlE=
          minLength: 44
          maxLength: 44
          pattern: ^[A-Za-z0-9+\/]{43}=|[A-Za-z0-9+\/]{44}$
    InformalPreLoadResponse:
      title: Informazioni per il caricamento file
      description: Per ogni richiesta che è stata fatta viene fornito un presigned URL e le  informazioni per usarlo.
      type: object
      properties:
        preloadIdx:
          description: per correlazione con la richiesta. Stringa alfanumerica con caratteri utilizzabili in un file.
          type: string
          minLength: 1
          maxLength: 512
          pattern: ^[a-zA-Z0-9._-]{1,512}$
        secret:
          description: Token aggiuntivo per far si che sia necessario intercettare anche gli  header e non solo l'URL di upload del contenuto del documento.
          example: AZ23RF12
          type: string
        httpMethod:
          description: Indica se per l'upload del contenuto file bisogna utilizzare il metodo PUT o POST
          type: string
          example: PUT
          enum:
            - POST
            - PUT
        url:
          description: URL a cui effettuare l'upload del contenuto del documento.
          type: string
          example: https://preloadpn.aws.amazon.......
        key:
          description: la chiave restituita sarà globalmente unica e andrà utilizzata nella richiesta  di notifica.
          example: PN_NOTIFICATION_ATTACHMENTS-0001-301W-B9CB-9U72-WIKD
          type: string
    NewMessageRequest:
      type: object
      required:
        - primaryMessage
      properties:
        primaryMessage:
          allOf:
            - $ref: '#/components/schemas/LocalizedContent'
            - description: Contenuto principale del messaggio, deve essere in lingua italiana
        additionalMessage:
          allOf:
            - $ref: '#/components/schemas/LocalizedContent'
            - description: Contenuto aggiuntivo del messaggio, opzionale, può essere in una lingua diversa dall'italiano
    MessageResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/NewMessageRequest'
        - type: object
          properties:
            messageId:
              description: Identificativo univoco del messaggio, da utilizzare per creare una notifica bonaria
              type: string
              format: uuid
            createdAt:
              description: Data e ora di creazione del messaggio
              type: string
              format: date-time
    NewInformalNotificationRequestStatusResponseV1:
      allOf:
        - $ref: '#/components/schemas/InformalNotificationRequestV1'
        - type: object
          required:
            - notificationRequestId
            - notificationRequestStatus
          properties:
            notificationRequestId:
              $ref: '#/components/schemas/NotificationRequestId'
            notificationRequestStatus:
              description: '- __WAITING__: in attesa di essere valutata - __ACCEPTED__: richiesta di notifica accettata, lo IUN è valorizzato - __REFUSED__: richiesta di notifica rifiutata, è valorizzato il campo _errors_'
              type: string
            retryAfter:
              type: integer
              format: int32
              description: Numero di secondi da attendere prima di effettuare una nuova richiesta per  la stessa entità; valorizzato quando lo status è __WAITING__.
            iun:
              $ref: '#/components/schemas/InformalIUN'
            errors:
              description: Elenco degli errori che hanno causato il rifiuto della richiesta di notifica
              type: array
              items:
                $ref: '#/components/schemas/NotificationRequestRefusedProblemError'
    NotificationRequestRefusedProblemError:
      allOf:
        - $ref: '#/components/schemas/ProblemError'
        - type: object
          required:
            - code
          properties:
            recIndex:
              description: Index destinatario notifica digitale
              type: integer
              format: int32
    PnStatusResponse:
      title: Stato attuale di PN
      description: Elenco delle funzionalità della piattaforma ed elenco dei disservizi noti e attivi  al momento della richiesta. I disservizi (_openIncidents_) segnalati sono al più uno  per funzionalità; gli attributi _endDate_ e _legalFactId_ non saranno valorizzati.
      type: object
      required:
        - functionalities
        - openIncidents
      properties:
        status:
          description: Bad Request
          example: 400
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: The server cannot process the request
          example: Bad Request
          maxLength: 64
          pattern: ^[ -~]{0,64}$
          type: string
        detail:
          description: The server cannot process the request
          example: Bad Request
          maxLength: 4096
          pattern: ^.{0,4096}$
          type: string
        functionalities:
          title: elenco funzionalità di PN
          description: Un array che comprende tutti i possibili valori dell'enum _PnFunctionality_
          type: array
          items:
            $ref: '#/components/schemas/PnFunctionality'
        openIncidents:
          title: elenco disservizi correnti
          description: Al più uno per funzionalità
          type: array
          items:
            $ref: '#/components/schemas/PnDowntimeEntry'
    PnFunctionality:
      title: Funzionalità di PN
      description: |-
        - __NOTIFICATION_CREATE__: la possibilità di creare nuove notifiche.
        - __NOTIFICATION_VISUALIZATION__: la possibilità di visualizzare le notifiche e scaricare gli atti. 
        - __NOTIFICATION_WORKFLOW__: l'avanzamento del processo di notifica.
      type: string
      enum:
        - NOTIFICATION_CREATE
        - NOTIFICATION_VISUALIZATION
        - NOTIFICATION_WORKFLOW
      x-enum-varnames:
        - NOTIFICATION_CREATE
        - NOTIFICATION_VISUALIZATION
        - NOTIFICATION_WORKFLOW
    PnFunctionalityStatus:
      type: string
      enum:
        - KO
        - OK
    PnDowntimeEntry:
      title: Dati relativi ad un disservizio di PN.
      type: object
      required:
        - functionality
        - status
        - startDate
      properties:
        functionality:
          $ref: '#/components/schemas/PnFunctionality'
        status:
          $ref: '#/components/schemas/PnFunctionalityStatus'
        startDate:
          title: data inizio disservizio
          type: string
          format: date-time
        endDate:
          title: data fine disservizio
          description: se il disservizio è ancora attivo questo campo sarà assente o con valore _null_
          type: string
          format: date-time
        legalFactId:
          title: id dell'atto opponibile a terzi
          description: Se assente o valorizzato _null_ indica che l'atto opponibile a terzi non è ancora disponibile. Questo avviene per i disservizi ancora aperti e per i disservizi  terminati da pochi minuti. <br/> Questo valore è da utilizzare con l'API _getLegalFact_ di questo stesso servizio.
          type: string
        fileAvailable:
          type: boolean
    Problem:
      properties:
        type:
          description: URI reference of type definition
          type: string
        status:
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          type: integer
          format: int32
          example: 503
          maximum: 600
          minimum: 100
          exclusiveMaximum: true
        title:
          description: A short, summary of the problem type. Written in english and readable
          example: Service Unavailable
          maxLength: 64
          pattern: ^[ -~]{0,64}$
          type: string
        detail:
          description: A human readable explanation of the problem.
          example: Request took too long to complete.
          maxLength: 4096
          pattern: ^.{0,4096}$
          type: string
        traceId:
          description: Internal support identifier associated to error
          example: 123e4567-e89b-12d3-a456-426614174000
          type: string
        timestamp:
          description: date and time referred to UTC
          example: '2022-07-27T12:22:33.444Z'
          type: string
          format: date-time
        errors:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/ProblemError'
      required:
        - status
        - errors
    ProblemError:
      properties:
        code:
          description: Internal code of the error, in human-readable format
          example: PN_PARAMETER_TOO_LONG | PN_PARAMETER_TOO_SHORT | PN_DUPLICATE_ENTRY | etc...
          type: string
        element:
          description: Parameter or request body field name for validation error
          example: body.order.item[2].quantity
          type: string
        detail:
          description: A human readable explanation specific to this occurrence of the problem.
          example: Parameter not valid
          maxLength: 1024
          type: string
      required:
        - code
    LocalizedContent:
      type: object
      required:
        - subject
        - longBody
        - language
      properties:
        subject:
          type: string
          minLength: 10
          maxLength: 120
          description: Titolo del messaggio (es. Oggetto della mail o intestazione IO)
          example: Sollecito di pagamento Tari 2023
        longBody:
          type: string
          minLength: 80
          maxLength: 9000
          description: Corpo esteso del messaggio in formato Markdown
          example: Gentile cittadino, la informiamo che dobbiamo raggiungere 80 caratteri per il corpo del messaggio, quindi questo è un esempio di testo che supera i 80 caratteri. Il messaggio può essere più lungo
        shortBody:
          type: string
          maxLength: 160
          description: Versione breve per SMS o anteprime
          example: 'Sollecito Tari: hai una nuova comunicazione da SEND.'
        language:
          type: string
          description: 'Lingua del messaggio. Valori accettati: - IT <br/> - DE <br/> - SL <br/> - FR <br/> DE (tedesco), SL (sloveno), FR (francese).'
    NotificationRequestId:
      type: string
      description: identificativo univoco di una richiesta di invio notifica, non è lo IUN
      maxLength: 36
      pattern: ^[A-Za-z0-9+/=]{36}$
    PaProtocolNumber:
      description: Numero di protocollo che la PA mittente assegna alla notifica stessa
      type: string
      pattern: ^.*$
      maxLength: 256
    IdempotenceToken:
      description: Identificativo utilizzabile dal chiamante per disambiguare differenti  "richieste di notificazione" effettuate con lo stesso numero di protocollo  (campo _paProtocolNumber_). Questo può essere necessario in caso di  "richiesta di notifica" rifiutata per errori nei codici di verifica degli allegati.
      type: string
      pattern: ^[ -~]*$
      maxLength: 256
    Denomination:
      description: 'Denominazione ente o persona fisica / ragione sociale. La codifica prevede i caratteri ISO LATIN 1, senza | e senza i caratteri di controllo, ovvero la seguente regexp: ^[ -{}~\u00A0-ÿ]*$'
      type: string
      minLength: 1
      maxLength: 88
      pattern: ^.*$
    TaxId:
      description: C.F. persona fisica o persona giuridica
      type: string
      minLength: 11
      maxLength: 16
      pattern: ^([A-Z]{6}[0-9LMNPQRSTUV]{2}[A-Z]{1}[0-9LMNPQRSTUV]{2}[A-Z]{1}[0-9LMNPQRSTUV]{3}[A-Z]{1})|([0-9]{11})$
    NotificationDigitalAddress:
      description: Indirizzo di invio della notifica
      required:
        - address
        - type
      type: object
      properties:
        type:
          type: string
          description: tipo di indirizzo PEC, REM, SERCQ, ...
          enum:
            - PEC
        address:
          type: string
          example: account@domain.it
          description: Indirizzo PEC o REM che il mittente della notifica intende utilizzare per  raggiungere il destinatario.
          pattern: ^(?:[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?|\[(?:(?:25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?|[a-zA-Z0-9-]*[a-zA-Z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])$
          maxLength: 320
    NotificationPhysicalAddress:
      description: Indirizzo fisico
      type: object
      required:
        - address
        - municipality
      properties:
        at:
          type: string
          description: Campo "presso" dell'indirizzo
          pattern: ^.*$
          maxLength: 44
        address:
          type: string
          description: Indirizzo del domicilio fisico
          pattern: ^.*$
          minLength: 2
          maxLength: 1024
        addressDetails:
          type: string
          description: Seconda riga dell'indirizzo fisico
          pattern: ^.*$
          maxLength: 1024
        zip:
          type: string
          description: Codice di avviamento postale. In caso di invio estero diventa facoltativo
          minLength: 0
          maxLength: 15
          pattern: ^(\w|\ |\-)*$
        municipality:
          type: string
          description: Comune
          pattern: ^.*$
          minLength: 2
          maxLength: 256
        municipalityDetails:
          type: string
          description: Frazione o località
          pattern: ^.*$
          maxLength: 256
        province:
          type: string
          description: Provincia
          pattern: ^.*$
          maxLength: 256
        foreignState:
          type: string
          description: Denominazione paese estero
          pattern: ^.*$
          maxLength: 256
    noticeCode:
      description: Payment notice number  numero avviso
      example: '302000100000019421'
      type: string
      maxLength: 18
      minLength: 18
      pattern: ^\d+$
    paTaxId:
      description: Payment PA fiscal code
      example: '77777777777'
      type: string
      maxLength: 11
      minLength: 11
      pattern: ^\d+$
    NotificationAttachmentDigests:
      description: Codici per la verifica del corretto caricamento di un allegato
      type: object
      required:
        - sha256
      properties:
        sha256:
          type: string
          description: Digest "sha256" della codifica binaria dell'allegato in base64
          example: jezIVxlG1M1woCSUngM6KipUN3/p8cG5RMIPnuEanlE=
          minLength: 44
          maxLength: 44
          pattern: ^[A-Za-z0-9+\/]{43}=|[A-Za-z0-9+\/]{44}$
    NotificationAttachmentBodyRef:
      description: Riferimento all'allegato precaricato
      required:
        - key
        - versionToken
      type: object
      properties:
        key:
          type: string
          description: Chiave in cui è stato salvato l'allegato
          maxLength: 512
          pattern: ^(safestorage:\/\/)?[A-Za-z0-9._-]+$
        versionToken:
          type: string
          description: Token per recuperare l'esatta istanza dell'allegato, che dovrà coincidere con l'__x-amz-version-id__ ottenuto nell'header della response in fase di upload del documento ad esso associato.
          pattern: ^.*$
          maxLength: 256
    NotificationAttachment:
      description: Un allegato della notifica.
      type: object
      required:
        - digests
        - contentType
        - ref
      properties:
        digests:
          $ref: '#/components/schemas/NotificationAttachmentDigests'
        contentType:
          type: string
          description: tipo di contenuto dell'allegato, supportato application/pdf
          minLength: 15
          maxLength: 15
          pattern: ^application\/pdf$
        ref:
          $ref: '#/components/schemas/NotificationAttachmentBodyRef'
    NotificationPaymentAttachment:
      description: Un modulo di pagamento allegato alla notifica
      allOf:
        - $ref: '#/components/schemas/NotificationAttachment'
    PagoPaPayment:
      title: Informazioni per effettuare il pagamento con sistema pagoPA
      description: |-
        Informazioni utili per effettuare il pagamento di una notifica, sono associate al destinatario perché le spese di notifica possono differire a seconda del canale di notifica utilizzato. <br/>
          - _noticeCode_: "codice avviso pagoPA" di pagamento del sistema pagoPA, usato per pagamento online.<br/>
          - _creditorTaxId_: codice fiscale dell'ente a cui fa riferimento il "codice avviso pagoPA". <br/>
          - _applyCost_: flag per indicare se l'avviso pagoPA deve contenere i costi di notifica. <br/>
          - _pagoPaForm_: riferimento al PDF contenete il bollettino pagoPA<br/>
      type: object
      required:
        - noticeCode
        - creditorTaxId
        - applyCost
      properties:
        noticeCode:
          $ref: '#/components/schemas/noticeCode'
        creditorTaxId:
          $ref: '#/components/schemas/paTaxId'
        applyCost:
          type: boolean
          nullable: false
          description: Flag per indicare se l'avviso pagoPa deve contenere i costi di notifica
        attachment:
          $ref: '#/components/schemas/NotificationPaymentAttachment'
    NotificationMetadataAttachment:
      description: Un metadato allegato della notifica.
      type: object
      required:
        - digests
        - contentType
        - ref
      properties:
        digests:
          $ref: '#/components/schemas/NotificationAttachmentDigests'
        contentType:
          type: string
          description: tipo di contenuto dell'allegato, supportato application/json
          minLength: 16
          maxLength: 16
          pattern: ^application\/json$
        ref:
          $ref: '#/components/schemas/NotificationAttachmentBodyRef'
    F24Payment:
      title: Informazioni per effettuare il pagamento tramite modello F24
      description: |-
        Informazioni utili per effettuare il pagamento di una notifica, sono associate al destinatario perché le spese di notifica possono differire a seconda del canale di notifica utilizzato. <br/>
          - _title_: titolo del documento pdf da mostrare all'utente .<br/>
          - _applyCost_: flag per indicare se il modello F24 deve contenere i costi di notifica.<br/>
          - _metadataAttachment_: riferimento ai metadati per la generazione del modello F24.<br/>
      type: object
      required:
        - title
        - applyCost
        - metadataAttachment
      properties:
        title:
          description: Titolo del documento pdf da mostrare all'utente
          type: string
        applyCost:
          type: boolean
          nullable: false
          description: Flag per indicare se il modello F24 deve contere i costi di notifica
        metadataAttachment:
          $ref: '#/components/schemas/NotificationMetadataAttachment'
    NotificationPaymentItem:
      minProperties: 1
      additionalProperties: false
      nullable: false
      properties:
        pagoPa:
          $ref: '#/components/schemas/PagoPaPayment'
        f24:
          $ref: '#/components/schemas/F24Payment'
    NotificationPayments:
      title: Pagamenti collegati alla notifica per il destinatario
      description: Lista dei pagamenti collegati alla notifica per il destinatario. Possono essere pagamenti rateali o alternativi
      type: array
      items:
        $ref: '#/components/schemas/NotificationPaymentItem'
    NotificationRecipientV24:
      description: Informazioni sui destinatari
      required:
        - denomination
        - recipientType
        - taxId
      type: object
      properties:
        recipientType:
          type: string
          description: 'Tipologia di destinatario: Persona Fisica (PF) o Persona Giuridica (PG)'
          enum:
            - PF
            - PG
        taxId:
          $ref: '#/components/schemas/TaxId'
        denomination:
          $ref: '#/components/schemas/Denomination'
        digitalDomicile:
          $ref: '#/components/schemas/NotificationDigitalAddress'
        physicalAddress:
          $ref: '#/components/schemas/NotificationPhysicalAddress'
        payments:
          $ref: '#/components/schemas/NotificationPayments'
    PagoPaPaymentBase:
      title: Informazioni per effettuare il pagamento con sistema pagoPA
      description: |-
        Informazioni utili per effettuare il pagamento di una notifica, sono associate al destinatario perché le spese di notifica possono differire a seconda del canale di notifica utilizzato. <br/>
          - _noticeCode_: "codice avviso pagoPA" di pagamento del sistema pagoPA, usato per pagamento online.<br/>
          - _creditorTaxId_: codice fiscale dell'ente a cui fa riferimento il "codice avviso pagoPA". <br/>
          - _attachment_: riferimento al PDF contenete il bollettino pagoPA<br/>
      type: object
      required:
        - noticeCode
        - creditorTaxId
        - amount
      properties:
        noticeCode:
          $ref: '#/components/schemas/noticeCode'
        creditorTaxId:
          $ref: '#/components/schemas/paTaxId'
        attachment:
          $ref: '#/components/schemas/NotificationPaymentAttachment'
        amount:
          type: integer
          format: int32
          description: Importo del pagamento in eurocent
          minimum: 0
        dueDate:
          type: string
          format: date-time
          description: Data di scadenza del pagamento. Il formato data deve essere ISO-8601 e fuso orario UTC
    InformalNotificationPaymentItem:
      description: Elemento di pagamento della notifica informale. Al momento è supportato esclusivamente il pagamento pagoPA.
      type: object
      additionalProperties: false
      required:
        - pagoPa
      properties:
        pagoPa:
          $ref: '#/components/schemas/PagoPaPaymentBase'
    InformalNotificationPayments:
      description: Lista dei pagamenti collegati alla notifica informale per il destinatario.
      type: array
      items:
        $ref: '#/components/schemas/InformalNotificationPaymentItem'
    InformalNotificationRecipientV1:
      description: Dati del destinatario specifici per una notifica informale, inclusi il riferimento al messaggio e i canali opzionali di contatto.
      allOf:
        - $ref: '#/components/schemas/NotificationRecipientV24'
        - type: object
          required:
            - messageId
          properties:
            payments:
              $ref: '#/components/schemas/InformalNotificationPayments'
            messageId:
              type: string
              format: uuid
              description: Identificativo del template di messaggio da utilizzare per il destinatario.
            email:
              type: string
              example: account@domain.it
              description: Indirizzo email che il mittente della notifica intende utilizzare per  raggiungere il destinatario.
              pattern: ^(?:[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?|\[(?:(?:25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?|[a-zA-Z0-9-]*[a-zA-Z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])$
              maxLength: 320
            phoneNumber:
              type: string
              example: '+3900000000'
              description: Numero di telefono che il mittente della notifica intende utilizzare per raggiungere il destinatario, espresso in formato internazionale con prefisso `+` oppure `00`.
              pattern: ^(\+|00)[1-9]\d{0,3}[\s.-]?\d{1,4}[\s.-]?\d{1,4}[\s.-]?\d{1,9}$
              maxLength: 30
            additionalLanguages:
              description: 'In questo campo è possibile definire la lingua addizionale (oltre a quella italiana) da utilizzare per l''invio del messaggio sui canali configurati.<br/> Le lingue accettate e dunque i valori possibili degli item dell''array sono: <br/> - DE <br/> - SL <br/> - FR <br/> DE (tedesco), SL (sloveno), FR (francese) Attualmente è possibile indicare un solo item e dunque una sola lingua aggiuntiva. Se non vengono indicate lingue aggiuntive la lingua utilizzata <br/> per l''invio del messaggio sui canali configurati sarà quella italiana. <br /> **Coerenza con messageId:** Se viene fornito un `messageId`, il messaggio identificato deve essere associato alla lingua indicata in questo campo. <br/>'
              type: array
              maxItems: 1
              items:
                type: string
    NotificationDocument:
      description: Un documento da notificare
      allOf:
        - $ref: '#/components/schemas/NotificationAttachment'
        - type: object
          properties:
            title:
              type: string
              description: Titolo del documento allegato. Stringa alfanumerica con caratteri utilizzabili in un nome file.
              minLength: 1
              maxLength: 512
              pattern: ^.*$
            docIdx:
              type: string
              description: Indice del documento partendo da 0.
              maxLength: 3
              pattern: ^\d+$
    InformalNotificationRequestV1:
      description: Dati necessari per richiedere la creazione di una notifica informale.
      type: object
      required:
        - senderDenomination
        - paProtocolNumber
        - subject
        - campaignId
        - recipients
      properties:
        senderDenomination:
          $ref: '#/components/schemas/Denomination'
        paProtocolNumber:
          $ref: '#/components/schemas/PaProtocolNumber'
        idempotenceToken:
          $ref: '#/components/schemas/IdempotenceToken'
        campaignId:
          type: string
          description: Identificativo della campagna che determina il workflow di invio.
        subject:
          type: string
          description: Oggetto della comunicazione mostrato nei riepiloghi.
        recipients:
          type: array
          description: Elenco dei destinatari della notifica informale.
          items:
            $ref: '#/components/schemas/InformalNotificationRecipientV1'
          minItems: 1
        documents:
          type: array
          description: Elenco dei documenti allegati alla notifica informale.
          items:
            $ref: '#/components/schemas/NotificationDocument'
        group:
          type: string
          description: Gruppo di utenti dell'ente mittente autorizzato a visualizzare la notifica.
          pattern: ^[ -~]*$
          maxLength: 1024
    InformalIUN:
      description: Identificativo Univoco Notifica per il dominio informale
      type: string
      minLength: 25
      maxLength: 25
      pattern: ^[A-Z]{4}-[A-Z]{4}-[A-Z]{4}-[0-9]{6}-[A-Z]{1}-[A-Z]{1}$
    NewNotificationResponse:
      title: Identificativi della richiesta di notifica
      description: Contiene le informazioni per identificare una richiesta di invio notifica che non è ancora stata accettata da Piattaforma notifiche.
      type: object
      required:
        - notificationRequestId
        - paProtocolNumber
      properties:
        notificationRequestId:
          $ref: '#/components/schemas/NotificationRequestId'
        paProtocolNumber:
          $ref: '#/components/schemas/PaProtocolNumber'
        idempotenceToken:
          $ref: '#/components/schemas/IdempotenceToken'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
